version: '3.7'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    init: true
    environment:
      - MONGO_INITDB_USERNAME="user"
      - MONGO_INITDB_PASSWORD="pass"
      - MONGODB_DATABASE="admin"
